Sprint 3
NikolayDimitriev/middle.messenger.praktikum.yandex pull request #4
Opened 2023-04-07 16:05 UTC by NikolayDimitriev

2023-04-08 07:50 UTC, agadoev requested changes
Привет, @NikolayDimitriev 

Спасибо за работу.

В коде встречается много nullable типов, без которых можно обойтись. Создатель null типа, уже назвал свое изобретение величайшей его ошибкой. Поэтому везде, где можно без него обойтись, лучше обходиться без него. Есть так же полезный [доклад](https://www.youtube.com/watch?v=YR5WdGrpoug) на эту тему от создателя языка Clojure, можешь посмотреть. 

Так же в одном месте я обнаружил нарушение инкапсуляции, но это не единственное место в коде, где оно встречается. Поправь везде, пожалуйста.

В остальном все ок, встречается unknown вместо any, что хорошо. Код читается легко.

Поправь комменты и двинемся дальше

2023-04-08 07:50 UTC, agadoev commented on src/components/addToChatUsersModal/index.ts
> +          UserController.searchUsers(inputValue);
если вызывать асинхронную функцию без ```await```, то поток исполнения остановится, ожидая завершения промиса, поэтому лучше добавить ```await```

2023-04-08 07:50 UTC, agadoev commented on src/utils/queryStringify.ts
> +}
можно записать попроще:
```suggestion
export function queryStringify(data: Record<string, string>): string {
  return "?" + Object
      .entries(data)
      .map(([key, value]) => `${key}=${value}`)
      .join("&")
}
```

2023-04-08 07:50 UTC, agadoev commented on src/typing/index.ts
> +};
Если это тип для странички изменения пароля, то ок, однако так же хорошая идея типизировать процессы. Например, у нас в комании есть приложения для SSO и мы типизируем процесс авторизации пользователя. (фиксить не надо, просто говорю, что можно типизировать не только модели данных, но и процессы)

2023-04-08 07:50 UTC, agadoev commented on src/typing/index.ts
> +};
поле ```data```  кажется очень абстрактным и я задаюсь вопросом, а так ли оно нужно? Может ```TUser``` и ```TUserProps``` - это один и тот же тип? Если хочется разделить, то можно написать вот так:
```suggestion
export type TUser = TUser
```
Но я бы оставил что-то одно, чтобы не путаться

2023-04-08 07:50 UTC, agadoev commented on src/typing/index.ts
> +    time: string;
время было бы удобнее обрабатывать, если бы оно было типа Date. Есть огромное количество форматов времени, и если оно представлено строкой, то непонятно, как его распарсить. Хорошо, если с бекенда оно приходит в ISO8601, однако лучше его распарсить на входе и уже в приложении оперировать типом Date. В будущем может добавиться локализация и нужно будет выводить время в разных форматах.

Как у нас сделано в проекте:
1. Есть слой ```api```, он генерируется автоматически, у тебя он тоже есть
2. Есть слой ```core```, в котором находятся доменные типы, там как раз время задано через тип Date
3. Есть слой эффектов, где связываются ```api``` и ```core```, и там как раз происходит маппинг данных, где можно распарсить string в Date

2023-04-08 07:50 UTC, agadoev commented on src/pages/profile/index.ts
>          class: 'profile-wrapper__btn profile-wrapper__btn--red',
Желательно конечно вынести все классы в шаблон. Если нужно поправить отображение, то логика меняться не должна. Т.е. если нужно изменить, например, цвет кнопки, должен быть изменен только .hbs или .css, но не .ts файл.

2023-04-08 07:50 UTC, agadoev commented on src/mock/mock.props.ts
> +// };
закомментированный код не должен быть в  мастерe

2023-04-08 07:50 UTC, agadoev commented on src/typing/index.ts
> +  events?: Record<string, (e?: Event) => void>;
```suggestion
  events?: Record<string, (e: Event) => void>;
```

Если можно обойтись без nullable-типов, надо обходиться без nullable-типов

2023-04-08 07:50 UTC, agadoev commented on src/typing/index.ts
> +  events?: Record<string, (e?: Event) => void>;
Если убрать тот optional operator, то из кода сразу исчезает [optional chaining operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html), что сразу повышает безопасность кода

2023-04-08 07:50 UTC, agadoev commented on src/pages/chats/index.ts
> +        },
Тут я вижу нарушение инкапсуляции компонента ChatModal. Давай объясню: у ChatModal есть какая-то внутряняя структура, например поле Input. Только ChatModal должен знать про эту струкутуру и про то, как с ней взаимодействовать. Сейчас очищение input'a происходит вне ChatModal, получается, что сокрытие данных нарушено. Это решается следующим образом:

1. В классе ChatModal нужно сделать публичный метод, например clear:
```
  public clear() {
    ((this.children.input as Input).getContent() as HTMLInputElement).value = ''
  }
```

2. переписать этот кусок кода
```suggestion
              (this.children.chatModal as ChatModal).clear()
```

3. Повторить сделанное для кода ниже, который как я понял, активирует модалку

2023-04-08 07:50 UTC, agadoev commented on src/core/Store.ts
> +  private _state: any = {};
Не очень понял, почему здесь ```any```, хотя есть тип ```TState```. Нужно типизировать стор

2023-04-08 07:50 UTC, agadoev commented on src/core/HTTPTransport.ts
> +  data?: any;
```suggestion
  data: unknown;
  headers: Record<string, string>
```

2023-04-08 07:50 UTC, agadoev commented on src/core/HTTPTransport.ts
> +}
подумай над тем, чтобы использовать [union type](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types) вместо enum'a. На мой взгляд они удобнее, а еще по ним можно делать exhaustive matching. Подробнее можно почитать [тут](https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant)

2023-04-08 11:36 UTC, NikolayDimitriev commented on src/api/BaseAPI.ts
> +  public abstract read?(identifier?: string | number): Promise<unknown>;
Долго не мог понять, но вроде разобрался. Добавил еще дженерик в ChatAPI, и уже в ChatsController передал TChatInfo[]

2023-04-08 11:38 UTC, NikolayDimitriev commented on src/components/InputsBlock/index.ts
> +        class: this.props.class ?? 'field__input',
Хм, мне кажется придется очень много переделывать. У меня получается Input, Button, Link максимально простые компоненты, используются во многих компонентах, поэтому разные атрибуты к ним прилетают

2023-04-08 11:40 UTC, NikolayDimitriev commented on src/components/addToChatUsersModal/index.ts
> +          UserController.searchUsers(inputValue);
Я добавил async/await. Только я думал потом не будет останавливаться, потому что у меня в самом контроллере все обернуто в try/catch и там же есть async/await

2023-04-08 11:41 UTC, NikolayDimitriev commented on src/pages/chats/index.ts
> +        },
Да тут фигню сделал, поправил в нескольких компонентах

2023-04-08 11:48 UTC, NikolayDimitriev commented on src/typing/index.ts
> +    time: string;
С бекенда приходит строка, как я понял в формате ISO8601, но я распарсил ее в компоненте message
https://ya-praktikum.tech/api/v2/swagger/#/Chats/get_chats

2023-04-10 04:04 UTC, agadoev commented on src/components/InputsBlock/index.ts
> +        class: this.props.class ?? 'field__input',
можешь попробовать параметризовать классы для этих компонентов, чтобы их через пропсы задавать

2023-04-10 04:05 UTC, agadoev commented on src/components/addToChatUsersModal/index.ts
> +          UserController.searchUsers(inputValue);
можно делать и через async/await, и через promise, но важно, чтобы в проекте было выбрано что-то одно. Если будут использоваться оба варианта, код в скором времени станет запутанным

2023-04-10 04:06 UTC, agadoev approved these changes
Привет, @NikolayDimitriev 

Спасибо за правки, сейчас все ок, работу принимаю. Удачи в следующем спринте)

2023-04-10 09:09 UTC, merged